Repository PickSa/picksa-server, pull requests merged in 2023-12, with the labels that each got.

#30 [배포] CI/CD 환경 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  src/main/java/com/picksa/picksaserver/global/config/PropertyConfig.java
  src/test/resources/application.yml
Labels: 🚀Deploy

#17 [질문] 후보 질문 생성 기능 구현
  src/main/java/com/picksa/picksaserver/applicant/ApplicantJpaRepository.java
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationEntity.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/request/EvaluationRequest.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/response/EvaluationResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/picksa/picksaserver/manager/ManagerJpaRepository.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionCreateResponse.java
  src/main/java/com/picksa/picksaserver/question/repository/QuestionRepository.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/test/java/com/picksa/picksaserver/PicksaServerApplicationTests.java
  src/test/resources/application.yml
Labels: 🦁Feature

#27 [질문] 질문 최종 결정/결정 취소 기능 구현
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationEntity.java
  src/main/java/com/picksa/picksaserver/global/config/PropertyConfig.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/QuestionDetermine.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionResponse.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/main/resources/application.yml
Labels: 🦁Feature

#38 [질문] 질문 최종 결정/결정 취소 기능 develop 병합
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationEntity.java
  src/main/java/com/picksa/picksaserver/global/config/PropertyConfig.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/QuestionDetermine.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionResponse.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/main/resources/application.yml
Labels: 🦁Feature

#40 [인가] 인가를 위한 filter 구현
  src/main/java/com/picksa/picksaserver/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtManager.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtValidationType.java
  src/main/java/com/picksa/picksaserver/global/auth/UserAuthentication.java
Labels: 🦁Feature

#43 [인증] 구글 소셜 로그인 기능 추가
  build.gradle
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantAllResponse.java
  src/main/java/com/picksa/picksaserver/applicant/service/ApplicantService.java
  src/main/java/com/picksa/picksaserver/auth/client/GoogleOAuthClient.java
  src/main/java/com/picksa/picksaserver/auth/client/OAuthClient.java
  src/main/java/com/picksa/picksaserver/auth/config/GoogleOAuthProperties.java
  src/main/java/com/picksa/picksaserver/auth/controller/AuthController.java
  src/main/java/com/picksa/picksaserver/auth/dto/GoogleOAuthToken.java
  src/main/java/com/picksa/picksaserver/auth/dto/GoogleUserInfoResponse.java
  src/main/java/com/picksa/picksaserver/auth/dto/OAuthUserInfoResponse.java
  src/main/java/com/picksa/picksaserver/auth/dto/SignInResponse.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthenticationUserNotRegisteredException.java
  src/main/java/com/picksa/picksaserver/auth/service/AuthCodeRequestProvider.java
  src/main/java/com/picksa/picksaserver/auth/service/GoogleAuthCodeRequestProvider.java
  src/main/java/com/picksa/picksaserver/auth/service/OAuthClientService.java
  src/main/java/com/picksa/picksaserver/auth/service/OAuthService.java
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationEntity.java
  src/main/java/com/picksa/picksaserver/evaluation/controller/EvaluationController.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/request/EvaluationRequest.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtManager.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtProperties.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtProvider.java
  src/main/java/com/picksa/picksaserver/global/config/PropertiesConfig.java
  src/main/java/com/picksa/picksaserver/global/config/PropertyConfig.java
  src/main/java/com/picksa/picksaserver/global/config/RestTemplateConfig.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
  src/main/java/com/picksa/picksaserver/manager/ManagerJpaRepository.java
  src/main/java/com/picksa/picksaserver/manager/repository/ManagerRepository.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/main/java/com/picksa/picksaserver/user/Position.java
  src/main/java/com/picksa/picksaserver/user/UserEntity.java
  src/main/java/com/picksa/picksaserver/user/UserJpaRepository.java
  src/main/java/com/picksa/picksaserver/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 🦁Feature

#35 [평가] 1차 최종결과 선택
  .gitignore
  src/main/java/com/picksa/picksaserver/applicant/ApplicantEntity.java
  src/main/java/com/picksa/picksaserver/applicant/Result.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantJpaRepository.java
  src/main/java/com/picksa/picksaserver/evaluation/controller/EvaluationController.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/request/DecideRequest.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/response/DecideResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/response/EvaluationResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/response/FinalEvaluationResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
Labels: 🦁Feature

#41 [질문] 질문 삭제 기능 구현
  src/main/java/com/picksa/picksaserver/applicant/service/ApplicantService.java
  src/main/java/com/picksa/picksaserver/auth/service/OAuthService.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
  src/main/java/com/picksa/picksaserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionDeleteResponse.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/main/java/com/picksa/picksaserver/user/repository/UserJpaRepository.java
  src/main/java/com/picksa/picksaserver/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 🦁Feature

#45 [지원자] 목록 조회 기능 phone 데이터 누락 반영
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantResponse.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantQueryRepositoryImpl.java
  src/main/java/com/picksa/picksaserver/user/controller/UserController.java
  src/main/java/com/picksa/picksaserver/user/dto/response/UserResponse.java
  src/main/java/com/picksa/picksaserver/user/service/UserService.java
Labels: 🐞Bug

#46 [질문] 질문 조회 기능 구현
  src/main/java/com/picksa/picksaserver/PicksaServerApplication.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/QuestionOrderCondition.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionResponse.java
  src/main/java/com/picksa/picksaserver/question/repository/QuestionQueryRepository.java
  src/main/java/com/picksa/picksaserver/question/repository/QuestionRepository.java
  src/main/java/com/picksa/picksaserver/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
Labels: 🦁Feature

#48 [배포] CORS 설정 추가
  src/main/java/com/picksa/picksaserver/global/config/WebConfig.java
Labels: 🚀Deploy

#49 [배포] CORS 설정 변경
  src/main/java/com/picksa/picksaserver/global/config/WebConfig.java
Labels: 🚀Deploy

#51 [설정] 브라우저의 Preflight 요청에 대해 401 에러가 발생하는 문제 해결
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
Labels: 🐞Bug, 🚀Deploy

#52 [지원자] 지원서 상세 조회 기능 구현
  src/main/java/com/picksa/picksaserver/applicant/AnswerEntity.java
  src/main/java/com/picksa/picksaserver/applicant/controller/ApplicantController.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/AnswerResponse.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantDetailResponse.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantResponse.java
  src/main/java/com/picksa/picksaserver/applicant/repository/AnswerRepository.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantRepository.java
  src/main/java/com/picksa/picksaserver/applicant/service/ApplicantService.java
  src/main/java/com/picksa/picksaserver/auth/client/GoogleOAuthClient.java
  src/main/java/com/picksa/picksaserver/auth/dto/GoogleUserInfoResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationJpaRepository.java
  src/main/java/com/picksa/picksaserver/evaluation/controller/EvaluationController.java
  src/main/java/com/picksa/picksaserver/evaluation/dto/response/DecideResponse.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/domain/Part.java
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/controller/TagController.java
  src/main/java/com/picksa/picksaserver/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/picksa/picksaserver/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
  src/main/java/com/picksa/picksaserver/question/service/TagService.java
Labels: 🦁Feature

#56 [User] 로그인한 사용자 정보 조회시 role 함께 반환하도록 변경
  src/main/java/com/picksa/picksaserver/user/Position.java
  src/main/java/com/picksa/picksaserver/user/dto/response/UserResponse.java
Labels: 🍀Refactor

#59 [인증] 인증인가 ErrorResponse 개선 후 permitAll API도 제한되는 문제 해결
  src/main/java/com/picksa/picksaserver/auth/exception/AuthErrorCode.java
  src/main/java/com/picksa/picksaserver/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtValidationType.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
Labels: 🐞Bug

#60 [공통] 예외 발생 시 응답 설정
  src/main/java/com/picksa/picksaserver/applicant/Result.java
  src/main/java/com/picksa/picksaserver/auth/controller/AuthController.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthErrorCode.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthenticationException.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthenticationUserNotExistException.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthenticationUserNotRegisteredException.java
  src/main/java/com/picksa/picksaserver/auth/exception/AuthorizationException.java
  src/main/java/com/picksa/picksaserver/auth/exception/JwtAuthenticationException.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/client/GoogleOAuthClient.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/client/OAuthClient.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/config/GoogleOAuthProperties.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/dto/GoogleOAuthToken.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/dto/GoogleUserInfoResponse.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/dto/OAuthUserInfoResponse.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/dto/SignInResponse.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/service/AuthCodeRequestProvider.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/service/GoogleAuthCodeRequestProvider.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/service/OAuthClientService.java
  src/main/java/com/picksa/picksaserver/auth/oAuth/service/OAuthService.java
  src/main/java/com/picksa/picksaserver/evaluation/EvaluationRepository.java
  src/main/java/com/picksa/picksaserver/evaluation/exception/EvaluationExceptionMessage.java
  src/main/java/com/picksa/picksaserver/evaluation/service/EvaluationService.java
  src/main/java/com/picksa/picksaserver/global/auth/AuthenticationExceptionHandlerFilter.java
  src/main/java/com/picksa/picksaserver/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/picksa/picksaserver/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/picksa/picksaserver/global/auth/CustomUserDetailsService.java
  src/main/java/com/picksa/picksaserver/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/picksa/picksaserver/global/config/PropertiesConfig.java
  src/main/java/com/picksa/picksaserver/global/exception/AuthorizationException.java
  src/main/java/com/picksa/picksaserver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/picksa/picksaserver/global/response/DefaultErrorResponse.java
Labels: 🍀Refactor

#62 [면접] 면접 일정 생성 기능 추가
  src/main/java/com/picksa/picksaserver/applicant/InterviewScheduleEntity.java
  src/main/java/com/picksa/picksaserver/applicant/controller/InterviewController.java
  src/main/java/com/picksa/picksaserver/applicant/dto/request/InterviewScheduleCreateRequest.java
  src/main/java/com/picksa/picksaserver/applicant/repository/InterviewScheduleRepository.java
  src/main/java/com/picksa/picksaserver/applicant/service/InterviewService.java
Labels: 🦁Feature
