Repository PickSa/picksa-server, pull requests merged in 2024-01, with the labels that each got.

#63 [질문] 질문 순서 조정
  src/main/java/com/picksa/picksaserver/question/QuestionEntity.java
  src/main/java/com/picksa/picksaserver/question/controller/QuestionController.java
  src/main/java/com/picksa/picksaserver/question/dto/request/QuestionUpdateSequenceRequest.java
  src/main/java/com/picksa/picksaserver/question/dto/response/QuestionUpdateSequenceResponse.java
  src/main/java/com/picksa/picksaserver/question/service/QuestionService.java
Labels: 🦁Feature

#64 [지원자] 합격자 인터뷰 가능 시간 조회 기능 구현
  src/main/java/com/picksa/picksaserver/applicant/ApplicantEntity.java
  src/main/java/com/picksa/picksaserver/applicant/controller/ApplicantController.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantScheduleResponse.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/ApplicantScheduleResponses.java
  src/main/java/com/picksa/picksaserver/applicant/dto/response/InterviewScheduleResponse.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantQueryRepository.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantQueryRepositoryImpl.java
  src/main/java/com/picksa/picksaserver/applicant/service/ApplicantService.java
  src/main/java/com/picksa/picksaserver/global/exception/GlobalExceptionHandler.java
Labels: 🦁Feature

#66 [질문] 질문 조회 수정
  src/main/java/com/picksa/picksaserver/question/repository/QuestionRepositoryImpl.java
Labels: 🐞Bug

#73 [인터뷰] 인터뷰 일정 생성 요청 형식 배열로 수정
  src/main/java/com/picksa/picksaserver/applicant/controller/InterviewController.java
  src/main/java/com/picksa/picksaserver/applicant/service/InterviewService.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
Labels: 🍀Refactor, 🦁Feature

#74 [인터뷰] 인터뷰 일정 조회 기능 구현
  src/main/java/com/picksa/picksaserver/applicant/controller/InterviewController.java
  src/main/java/com/picksa/picksaserver/applicant/service/InterviewService.java
  src/main/java/com/picksa/picksaserver/global/config/WebSecurityConfig.java
Labels: 🦁Feature

#76 [지원자] 지원자 전체 조회 기능 정렬 방식 수정
  src/main/java/com/picksa/picksaserver/applicant/controller/ApplicantController.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantQueryRepository.java
  src/main/java/com/picksa/picksaserver/applicant/repository/ApplicantQueryRepositoryImpl.java
  src/main/java/com/picksa/picksaserver/applicant/service/ApplicantService.java
Labels: 🐞Bug
